### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by stosdimayual** [denis660/laravel-centrifugo#22]
I would like to request support for Laravel 11. As Laravel 11 brings new features and improvements, it would be beneficial for the community to have this project compatible with the latest version. Specifically, support for Laravel 11 would help us leverage the new functionalities and maintain up-to-date security standards.

**Comment by denis660** [comment]
Hello. I have taken on this task and will try to update the package this month.

**Comment by wasiqaftab** [comment]
@denis660 is there any update on this

**Comment by geras332** [comment]
@denis660 is there any update on this?

**Comment by denis660** [comment]
> @denis660 is there any update on this?

Hello.
The package is ready for Laravel version 11, now I am setting up automatic tests

**Comment by geras332** [comment]
Problem 1
    - denis660/laravel-centrifugo[1.0.1, ..., 1.0.5] require laravel/framework ^5.6|^6.0|^7.0|^8.0 -> found laravel/framework[v5.6.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9).
    - denis660/laravel-centrifugo 1.0.6 requires laravel/framework ^6.20.26|^7.0|^8.0 -> found laravel/framework[v6.20.26, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9).
    - denis660/laravel-centrifugo[1.0.7, 2.0.0] require laravel/framework ^7.30.4|^8.0 -> found laravel/framework[v7.30.4, v7.30.5, v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9).
    - denis660/laravel-centrifugo[2.1, 3.0, ..., 3.0.1] require laravel/framework ^8.75.0|^9.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9).
    - denis660/laravel-centrifugo 3.1 requires laravel/framework ^8.75.0|^9.0|^10.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but it conflicts with your root composer.json require (^11.9).
    - Root composer.json requires denis660/laravel-centrifugo * -> satisfiable by denis660/laravel-centrifugo[1.0.1, ..., 1.0.7, 2.0.0, 2.1, 3.0, 3.0.1, 3.1].
    
    why so?

**Comment by geras332** [comment]
> Problem 1 - denis660/laravel-centrifugo[1.0.1, ..., 1.0.5] require laravel/framework ^5.6|^6.0|^7.0|^8.0 -> found laravel/framework[v5.6.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo 1.0.6 requires laravel/framework ^6.20.26|^7.0|^8.0 -> found laravel/framework[v6.20.26, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo[1.0.7, 2.0.0] require laravel/framework ^7.30.4|^8.0 -> found laravel/framework[v7.30.4, v7.30.5, v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo[2.1, 3.0, ..., 3.0.1] require laravel/framework ^8.75.0|^9.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo 3.1 requires laravel/framework ^8.75.0|^9.0|^10.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but it conflicts with your root composer.json require (^11.9). - Root composer.json requires denis660/laravel-centrifugo * -> satisfiable by denis660/laravel-centrifugo[1.0.1, ..., 1.0.7, 2.0.0, 2.1, 3.0, 3.0.1, 3.1].
> 
> ```
> why so?
> ```

how can I solve the problem?

**Comment by sneycampos** [comment]
> Problem 1 - denis660/laravel-centrifugo[1.0.1, ..., 1.0.5] require laravel/framework ^5.6|^6.0|^7.0|^8.0 -> found laravel/framework[v5.6.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo 1.0.6 requires laravel/framework ^6.20.26|^7.0|^8.0 -> found laravel/framework[v6.20.26, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo[1.0.7, 2.0.0] require laravel/framework ^7.30.4|^8.0 -> found laravel/framework[v7.30.4, v7.30.5, v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo[2.1, 3.0, ..., 3.0.1] require laravel/framework ^8.75.0|^9.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo 3.1 requires laravel/framework ^8.75.0|^9.0|^10.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but it conflicts with your root composer.json require (^11.9). - Root composer.json requires denis660/laravel-centrifugo * -> satisfiable by denis660/laravel-centrifugo[1.0.1, ..., 1.0.7, 2.0.0, 2.1, 3.0, 3.0.1, 3.1].
> 
> ```
> why so?
> ```

this is not related to the package, read the error messages and try to solve.

**Comment by denis660** [comment]
> > Problem 1 - denis660/laravel-centrifugo[1.0.1, ..., 1.0.5] require laravel/framework ^5.6|^6.0|^7.0|^8.0 -> found laravel/framework[v5.6.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo 1.0.6 requires laravel/framework ^6.20.26|^7.0|^8.0 -> found laravel/framework[v6.20.26, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo[1.0.7, 2.0.0] require laravel/framework ^7.30.4|^8.0 -> found laravel/framework[v7.30.4, v7.30.5, v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo[2.1, 3.0, ..., 3.0.1] require laravel/framework ^8.75.0|^9.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but it conflicts with your root composer.json require (^11.9). - denis660/laravel-centrifugo 3.1 requires laravel/framework ^8.75.0|^9.0|^10.0 -> found laravel/framework[v8.75.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.22] but it conflicts with your root composer.json require (^11.9). - Root composer.json requires denis660/laravel-centrifugo * -> satisfiable by denis660/laravel-centrifugo[1.0.1, ..., 1.0.7, 2.0.0, 2.1, 3.0, 3.0.1, 3.1].
> > ```
> > why so?
> > ```
> 
> this is not related to the package, read the error messages and try to solve.

All issues are fixed, you can update
