### ISSUE TITLE
Failed to open stream: No such file or directory (broadcasting.php)

### ISSUE THREAD

**Issue by rawezhcode** [denis660/laravel-centrifugo#24]
![image](https://github.com/user-attachments/assets/420ebbcb-8733-4ded-a582-b765a3869371)

**Comment by denis660** [comment]
> ![image](https://private-user-images.githubusercontent.com/53620168/374675186-420ebbcb-8733-4ded-a582-b765a3869371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTM5OTAsIm5iZiI6MTcyODQ5MzY5MCwicGF0aCI6Ii81MzYyMDE2OC8zNzQ2NzUxODYtNDIwZWJiY2ItODczMy00ZGVkLWE1ODItYjc2NWEzODY5MzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE3MDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDkyN2RkNWVhM2IzYzI1NmM4M2Y5NzcwYWQ3NjExZTc2ZTk0MWMwNDQzMGIwNjJmYzIwNGNlMTAzOTRlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sVUwRgvyBZjvsgasIYJHbbuhLt7-eYAxsCoVxxiqbx8)

```
php artisan install:broadcasting
```

**Comment by rawezhcode** [comment]
solved .
