### ISSUE TITLE
Centrifugo v3 compatibility

### ISSUE THREAD

**Issue by FZambia** [denis660/laravel-centrifugo#9]
Hello! Currently readme states that this package:

```
Compatible with latest Centrifugo 2.8.5
```

Recently [we released Centrifugo v3](https://centrifugal.dev/blog/2021/08/31/hello-centrifugo-v3) with many improvements and new features. Unfortunately there are also several backwards incompatible changes. Everything described in [Migrating to v3](https://centrifugal.dev/docs/getting-started/migration_v3) guide.

Regarding this package I noticed the following things to be updated:

* Response format of `channels` API method changed, and it now accepts `pattern` argument
* Behavior of `history` API changed - it does not return publications by default, only current stream position, to return publications `limit` argument must be set to a value greater than `0`. 
* Some additional fields added  to `publish`, `broadcast`, `history` methods (though new params fields do not break requests, just extend functionality)
* Also, some deprecated option names like `secret` now removed from Centrifugo, it's now `token_hmac_secret_key` - so maybe this package should match updated option names.

Would be awesome to have `laravel-centrifugo` inherit all of this. I am ready to help answering any questions during migration.

And thanks for an awesome package @denis660!

**Comment by denis660** [comment]
Thanks! I will definitely update to v3

**Comment by denis660** [comment]
Сделал обновление до Centrifugo  v 3
https://github.com/denis660/laravel-centrifugo/releases/tag/2.0.0

**Comment by FZambia** [comment]
Thanks!
